<?php

namespace Database\Seeders;

use App\Models\Upazila;
use Faker\Generator;
use Illuminate\Database\Seeder;

class UpazilaSeeder extends Seeder
{
    public function run(Generator $faker): void
    {
        $upazilas = array(
            array("name"=>"Debidwar", "district_id"=>"1", "is_active"=>"1", "name_bn"=>"দেবিদ্বার"),
            array("name"=>"Barura", "district_id"=>"1", "is_active"=>"1", "name_bn"=>"বরুড়া"),
            array("name"=>"Brahmanpara", "district_id"=>"1", "is_active"=>"1", "name_bn"=>"ব্রাহ্মণপাড়া"),
            array("name"=>"Chandina", "district_id"=>"1", "is_active"=>"1", "name_bn"=>"চান্দিনা"),
            array("name"=>"Chauddagram", "district_id"=>"1", "is_active"=>"1", "name_bn"=>"চৌদ্দগ্রাম"),
            array("name"=>"Daudkandi", "district_id"=>"1", "is_active"=>"1", "name_bn"=>"দাউদকান্দি"),
            array("name"=>"Homna", "district_id"=>"1", "is_active"=>"1", "name_bn"=>"হোমনা"),
            array("name"=>"Laksam", "district_id"=>"1", "is_active"=>"1", "name_bn"=>"লাকসাম"),
            array("name"=>"Muradnagar", "district_id"=>"1", "is_active"=>"1", "name_bn"=>"মুরাদনগর"),
            array("name"=>"Nangalkot", "district_id"=>"1", "is_active"=>"1", "name_bn"=>"নাঙ্গলকোট"),
            array("name"=>"Comilla Sadar", "district_id"=>"1", "is_active"=>"1", "name_bn"=>"কুমিল্লা সদর"),
            array("name"=>"Meghna", "district_id"=>"1", "is_active"=>"1", "name_bn"=>"মেঘনা"),
            array("name"=>"Monohargonj", "district_id"=>"1", "is_active"=>"1", "name_bn"=>"মনোহরগঞ্জ"),
            array("name"=>"Sadarsouth", "district_id"=>"1", "is_active"=>"1", "name_bn"=>"সদর দক্ষিণ"),
            array("name"=>"Titas", "district_id"=>"1", "is_active"=>"1", "name_bn"=>"তিতাস"),
            array("name"=>"Burichang", "district_id"=>"1", "is_active"=>"1", "name_bn"=>"বুড়িচং"),
            array("name"=>"Lalmai", "district_id"=>"1", "is_active"=>"1", "name_bn"=>"লালমাই"),
            array("name"=>"Chhagalnaiya", "district_id"=>"2", "is_active"=>"1", "name_bn"=>"ছাগলনাইয়া"),
            array("name"=>"Feni Sadar", "district_id"=>"2", "is_active"=>"1", "name_bn"=>"ফেনী সদর"),
            array("name"=>"Sonagazi", "district_id"=>"2", "is_active"=>"1", "name_bn"=>"সোনাগাজী"),
            array("name"=>"Fulgazi", "district_id"=>"2", "is_active"=>"1", "name_bn"=>"ফুলগাজী"),
            array("name"=>"Parshuram", "district_id"=>"2", "is_active"=>"1", "name_bn"=>"পরশুরাম"),
            array("name"=>"Daganbhuiyan", "district_id"=>"2", "is_active"=>"1", "name_bn"=>"দাগনভূঞা"),
            array("name"=>"Brahmanbaria Sadar", "district_id"=>"3", "is_active"=>"1", "name_bn"=>"ব্রাহ্মণবাড়িয়া সদর"),
            array("name"=>"Kasba", "district_id"=>"3", "is_active"=>"1", "name_bn"=>"কসবা"),
            array("name"=>"Nasirnagar", "district_id"=>"3", "is_active"=>"1", "name_bn"=>"নাসিরনগর"),
            array("name"=>"Sarail", "district_id"=>"3", "is_active"=>"1", "name_bn"=>"সরাইল"),
            array("name"=>"Ashuganj", "district_id"=>"3", "is_active"=>"1", "name_bn"=>"আশুগঞ্জ"),
            array("name"=>"Akhaura", "district_id"=>"3", "is_active"=>"1", "name_bn"=>"আখাউড়া"),
            array("name"=>"Nabinagar", "district_id"=>"3", "is_active"=>"1", "name_bn"=>"নবীনগর"),
            array("name"=>"Bancharampur", "district_id"=>"3", "is_active"=>"1", "name_bn"=>"বাঞ্ছারামপুর"),
            array("name"=>"Bijoynagar", "district_id"=>"3", "is_active"=>"1", "name_bn"=>"বিজয়নগর"),
            array("name"=>"Rangamati Sadar", "district_id"=>"4", "is_active"=>"1", "name_bn"=>"রাঙ্গামাটি সদর"),
            array("name"=>"Kaptai", "district_id"=>"4", "is_active"=>"1", "name_bn"=>"কাপ্তাই"),
            array("name"=>"Kawkhali", "district_id"=>"4", "is_active"=>"1", "name_bn"=>"কাউখালী"),
            array("name"=>"Baghaichari", "district_id"=>"4", "is_active"=>"1", "name_bn"=>"বাঘাইছড়ি"),
            array("name"=>"Barkal", "district_id"=>"4", "is_active"=>"1", "name_bn"=>"বরকল"),
            array("name"=>"Langadu", "district_id"=>"4", "is_active"=>"1", "name_bn"=>"লংগদু"),
            array("name"=>"Rajasthali", "district_id"=>"4", "is_active"=>"1", "name_bn"=>"রাজস্থলী"),
            array("name"=>"Belaichari", "district_id"=>"4", "is_active"=>"1", "name_bn"=>"বিলাইছড়ি"),
            array("name"=>"Juraichari", "district_id"=>"4", "is_active"=>"1", "name_bn"=>"জুরাছড়ি"),
            array("name"=>"Naniarchar", "district_id"=>"4", "is_active"=>"1", "name_bn"=>"নানিয়ারচর"),
            array("name"=>"Noakhali Sadar", "district_id"=>"5", "is_active"=>"1", "name_bn"=>"নোয়াখালী সদর"),
            array("name"=>"Companiganj", "district_id"=>"5", "is_active"=>"1", "name_bn"=>"কোম্পানীগঞ্জ"),
            array("name"=>"Begumganj", "district_id"=>"5", "is_active"=>"1", "name_bn"=>"বেগমগঞ্জ"),
            array("name"=>"Hatia", "district_id"=>"5", "is_active"=>"1", "name_bn"=>"হাতিয়া"),
            array("name"=>"Subarnachar", "district_id"=>"5", "is_active"=>"1", "name_bn"=>"সুবর্ণচর"),
            array("name"=>"Kabirhat", "district_id"=>"5", "is_active"=>"1", "name_bn"=>"কবিরহাট"),
            array("name"=>"Senbug", "district_id"=>"5", "is_active"=>"1", "name_bn"=>"সেনবাগ"),
            array("name"=>"Chatkhil", "district_id"=>"5", "is_active"=>"1", "name_bn"=>"চাটখিল"),
            array("name"=>"Sonaimori", "district_id"=>"5", "is_active"=>"1", "name_bn"=>"সোনাইমুড়ী"),
            array("name"=>"Haimchar", "district_id"=>"6", "is_active"=>"1", "name_bn"=>"হাইমচর"),
            array("name"=>"Kachua", "district_id"=>"6", "is_active"=>"1", "name_bn"=>"কচুয়া"),
            array("name"=>"Shahrasti", "district_id"=>"6", "is_active"=>"1", "name_bn"=>"শাহরাস্তি	"),
            array("name"=>"Chandpur Sadar", "district_id"=>"6", "is_active"=>"1", "name_bn"=>"চাঁদপুর সদর"),
            array("name"=>"Matlab South", "district_id"=>"6", "is_active"=>"1", "name_bn"=>"মতলব দক্ষিণ"),
            array("name"=>"Hajiganj", "district_id"=>"6", "is_active"=>"1", "name_bn"=>"হাজীগঞ্জ"),
            array("name"=>"Matlab North", "district_id"=>"6", "is_active"=>"1", "name_bn"=>"মতলব উত্তর"),
            array("name"=>"Faridgonj", "district_id"=>"6", "is_active"=>"1", "name_bn"=>"ফরিদগঞ্জ"),
            array("name"=>"Lakshmipur Sadar", "district_id"=>"7", "is_active"=>"1", "name_bn"=>"লক্ষ্মীপুর সদর"),
            array("name"=>"Kamalnagar", "district_id"=>"7", "is_active"=>"1", "name_bn"=>"কমলনগর"),
            array("name"=>"Raipur", "district_id"=>"7", "is_active"=>"1", "name_bn"=>"রায়পুর"),
            array("name"=>"Ramgati", "district_id"=>"7", "is_active"=>"1", "name_bn"=>"রামগতি"),
            array("name"=>"Ramganj", "district_id"=>"7", "is_active"=>"1", "name_bn"=>"রামগঞ্জ"),
            array("name"=>"Rangunia", "district_id"=>"8", "is_active"=>"1", "name_bn"=>"রাঙ্গুনিয়া"),
            array("name"=>"Sitakunda", "district_id"=>"8", "is_active"=>"1", "name_bn"=>"সীতাকুন্ড"),
            array("name"=>"Mirsharai", "district_id"=>"8", "is_active"=>"1", "name_bn"=>"মীরসরাই"),
            array("name"=>"Patiya", "district_id"=>"8", "is_active"=>"1", "name_bn"=>"পটিয়া"),
            array("name"=>"Sandwip", "district_id"=>"8", "is_active"=>"1", "name_bn"=>"সন্দ্বীপ"),
            array("name"=>"Banshkhali", "district_id"=>"8", "is_active"=>"1", "name_bn"=>"বাঁশখালী"),
            array("name"=>"Boalkhali", "district_id"=>"8", "is_active"=>"1", "name_bn"=>"বোয়ালখালী"),
            array("name"=>"Anwara", "district_id"=>"8", "is_active"=>"1", "name_bn"=>"আনোয়ারা"),
            array("name"=>"Chandanaish", "district_id"=>"8", "is_active"=>"1", "name_bn"=>"চন্দনাইশ"),
            array("name"=>"Satkania", "district_id"=>"8", "is_active"=>"1", "name_bn"=>"সাতকানিয়া"),
            array("name"=>"Lohagara", "district_id"=>"8", "is_active"=>"1", "name_bn"=>"লোহাগাড়া"),
            array("name"=>"Hathazari", "district_id"=>"8", "is_active"=>"1", "name_bn"=>"হাটহাজারী"),
            array("name"=>"Fatikchhari", "district_id"=>"8", "is_active"=>"1", "name_bn"=>"ফটিকছড়ি"),
            array("name"=>"Raozan", "district_id"=>"8", "is_active"=>"1", "name_bn"=>"রাউজান"),
            array("name"=>"Karnafuli", "district_id"=>"8", "is_active"=>"1", "name_bn"=>"কর্ণফুলী"),
            array("name"=>"Coxsbazar Sadar", "district_id"=>"9", "is_active"=>"1", "name_bn"=>"কক্সবাজার সদর"),
            array("name"=>"Chakaria", "district_id"=>"9", "is_active"=>"1", "name_bn"=>"চকরিয়া"),
            array("name"=>"Kutubdia", "district_id"=>"9", "is_active"=>"1", "name_bn"=>"কুতুবদিয়া"),
            array("name"=>"Ukhiya", "district_id"=>"9", "is_active"=>"1", "name_bn"=>"উখিয়া"),
            array("name"=>"Moheshkhali", "district_id"=>"9", "is_active"=>"1", "name_bn"=>"মহেশখালী"),
            array("name"=>"Pekua", "district_id"=>"9", "is_active"=>"1", "name_bn"=>"পেকুয়া"),
            array("name"=>"Ramu", "district_id"=>"9", "is_active"=>"1", "name_bn"=>"রামু"),
            array("name"=>"Teknaf", "district_id"=>"9", "is_active"=>"1", "name_bn"=>"টেকনাফ"),
            array("name"=>"Khagrachhari Sadar", "district_id"=>"10", "is_active"=>"1", "name_bn"=>"খাগড়াছড়ি সদর"),
            array("name"=>"Dighinala", "district_id"=>"10", "is_active"=>"1", "name_bn"=>"দিঘীনালা"),
            array("name"=>"Panchari", "district_id"=>"10", "is_active"=>"1", "name_bn"=>"পানছড়ি"),
            array("name"=>"Laxmichhari", "district_id"=>"10", "is_active"=>"1", "name_bn"=>"লক্ষীছড়ি"),
            array("name"=>"Mohalchari", "district_id"=>"10", "is_active"=>"1", "name_bn"=>"মহালছড়ি"),
            array("name"=>"Manikchari", "district_id"=>"10", "is_active"=>"1", "name_bn"=>"মানিকছড়ি"),
            array("name"=>"Ramgarh", "district_id"=>"10", "is_active"=>"1", "name_bn"=>"রামগড়"),
            array("name"=>"Matiranga", "district_id"=>"10", "is_active"=>"1", "name_bn"=>"মাটিরাঙ্গা"),
            array("name"=>"Guimara", "district_id"=>"10", "is_active"=>"1", "name_bn"=>"গুইমারা"),
            array("name"=>"Bandarban Sadar", "district_id"=>"11", "is_active"=>"1", "name_bn"=>"বান্দরবান সদর"),
            array("name"=>"Alikadam", "district_id"=>"11", "is_active"=>"1", "name_bn"=>"আলীকদম"),
            array("name"=>"Naikhongchhari", "district_id"=>"11", "is_active"=>"1", "name_bn"=>"নাইক্ষ্যংছড়ি"),
            array("name"=>"Rowangchhari", "district_id"=>"11", "is_active"=>"1", "name_bn"=>"রোয়াংছড়ি"),
            array("name"=>"Lama", "district_id"=>"11", "is_active"=>"1", "name_bn"=>"লামা"),
            array("name"=>"Ruma", "district_id"=>"11", "is_active"=>"1", "name_bn"=>"রুমা"),
            array("name"=>"Thanchi", "district_id"=>"11", "is_active"=>"1", "name_bn"=>"থানচি"),
            array("name"=>"Belkuchi", "district_id"=>"12", "is_active"=>"1", "name_bn"=>"বেলকুচি"),
            array("name"=>"Chauhali", "district_id"=>"12", "is_active"=>"1", "name_bn"=>"চৌহালি"),
            array("name"=>"Kamarkhand", "district_id"=>"12", "is_active"=>"1", "name_bn"=>"কামারখন্দ"),
            array("name"=>"Kazipur", "district_id"=>"12", "is_active"=>"1", "name_bn"=>"কাজীপুর"),
            array("name"=>"Raigonj", "district_id"=>"12", "is_active"=>"1", "name_bn"=>"রায়গঞ্জ"),
            array("name"=>"Shahjadpur", "district_id"=>"12", "is_active"=>"1", "name_bn"=>"শাহজাদপুর"),
            array("name"=>"Sirajganj Sadar", "district_id"=>"12", "is_active"=>"1", "name_bn"=>"সিরাজগঞ্জ সদর"),
            array("name"=>"Tarash", "district_id"=>"12", "is_active"=>"1", "name_bn"=>"তাড়াশ"),
            array("name"=>"Ullapara", "district_id"=>"12", "is_active"=>"1", "name_bn"=>"উল্লাপাড়া"),
            array("name"=>"Sujanagar", "district_id"=>"13", "is_active"=>"1", "name_bn"=>"সুজানগর"),
            array("name"=>"Ishurdi", "district_id"=>"13", "is_active"=>"1", "name_bn"=>"ঈশ্বরদী"),
            array("name"=>"Bhangura", "district_id"=>"13", "is_active"=>"1", "name_bn"=>"ভাঙ্গুড়া"),
            array("name"=>"Pabna Sadar", "district_id"=>"13", "is_active"=>"1", "name_bn"=>"পাবনা সদর"),
            array("name"=>"Bera", "district_id"=>"13", "is_active"=>"1", "name_bn"=>"বেড়া"),
            array("name"=>"Atghoria", "district_id"=>"13", "is_active"=>"1", "name_bn"=>"আটঘরিয়া"),
            array("name"=>"Chatmohar", "district_id"=>"13", "is_active"=>"1", "name_bn"=>"চাটমোহর"),
            array("name"=>"Santhia", "district_id"=>"13", "is_active"=>"1", "name_bn"=>"সাঁথিয়া"),
            array("name"=>"Faridpur", "district_id"=>"13", "is_active"=>"1", "name_bn"=>"ফরিদপুর"),
            array("name"=>"Kahaloo", "district_id"=>"14", "is_active"=>"1", "name_bn"=>"কাহালু"),
            array("name"=>"Bogra Sadar", "district_id"=>"14", "is_active"=>"1", "name_bn"=>"বগুড়া সদর"),
            array("name"=>"Shariakandi", "district_id"=>"14", "is_active"=>"1", "name_bn"=>"সারিয়াকান্দি"),
            array("name"=>"Shajahanpur", "district_id"=>"14", "is_active"=>"1", "name_bn"=>"শাজাহানপুর"),
            array("name"=>"Dupchanchia", "district_id"=>"14", "is_active"=>"1", "name_bn"=>"দুপচাচিঁয়া"),
            array("name"=>"Adamdighi", "district_id"=>"14", "is_active"=>"1", "name_bn"=>"আদমদিঘি"),
            array("name"=>"Nondigram", "district_id"=>"14", "is_active"=>"1", "name_bn"=>"নন্দিগ্রাম"),
            array("name"=>"Sonatala", "district_id"=>"14", "is_active"=>"1", "name_bn"=>"সোনাতলা"),
            array("name"=>"Dhunot", "district_id"=>"14", "is_active"=>"1", "name_bn"=>"ধুনট"),
            array("name"=>"Gabtali", "district_id"=>"14", "is_active"=>"1", "name_bn"=>"গাবতলী"),
            array("name"=>"Sherpur", "district_id"=>"14", "is_active"=>"1", "name_bn"=>"শেরপুর"),
            array("name"=>"Shibganj", "district_id"=>"14", "is_active"=>"1", "name_bn"=>"শিবগঞ্জ"),
            array("name"=>"Paba", "district_id"=>"15", "is_active"=>"1", "name_bn"=>"পবা"),
            array("name"=>"Durgapur", "district_id"=>"15", "is_active"=>"1", "name_bn"=>"দুর্গাপুর"),
            array("name"=>"Mohonpur", "district_id"=>"15", "is_active"=>"1", "name_bn"=>"মোহনপুর"),
            array("name"=>"Charghat", "district_id"=>"15", "is_active"=>"1", "name_bn"=>"চারঘাট"),
            array("name"=>"Puthia", "district_id"=>"15", "is_active"=>"1", "name_bn"=>"পুঠিয়া"),
            array("name"=>"Bagha", "district_id"=>"15", "is_active"=>"1", "name_bn"=>"বাঘা"),
            array("name"=>"Godagari", "district_id"=>"15", "is_active"=>"1", "name_bn"=>"গোদাগাড়ী"),
            array("name"=>"Tanore", "district_id"=>"15", "is_active"=>"1", "name_bn"=>"তানোর"),
            array("name"=>"Bagmara", "district_id"=>"15", "is_active"=>"1", "name_bn"=>"বাগমারা"),
            array("name"=>"Natore Sadar", "district_id"=>"16", "is_active"=>"1", "name_bn"=>"নাটোর সদর"),
            array("name"=>"Singra", "district_id"=>"16", "is_active"=>"1", "name_bn"=>"সিংড়া"),
            array("name"=>"Baraigram", "district_id"=>"16", "is_active"=>"1", "name_bn"=>"বড়াইগ্রাম"),
            array("name"=>"Bagatipara", "district_id"=>"16", "is_active"=>"1", "name_bn"=>"বাগাতিপাড়া"),
            array("name"=>"Lalpur", "district_id"=>"16", "is_active"=>"1", "name_bn"=>"লালপুর"),
            array("name"=>"Gurudaspur", "district_id"=>"16", "is_active"=>"1", "name_bn"=>"গুরুদাসপুর"),
            array("name"=>"Naldanga", "district_id"=>"16", "is_active"=>"1", "name_bn"=>"নলডাঙ্গা"),
            array("name"=>"Akkelpur", "district_id"=>"17", "is_active"=>"1", "name_bn"=>"আক্কেলপুর"),
            array("name"=>"Kalai", "district_id"=>"17", "is_active"=>"1", "name_bn"=>"কালাই"),
            array("name"=>"Khetlal", "district_id"=>"17", "is_active"=>"1", "name_bn"=>"ক্ষেতলাল"),
            array("name"=>"Panchbibi", "district_id"=>"17", "is_active"=>"1", "name_bn"=>"পাঁচবিবি"),
            array("name"=>"Joypurhat Sadar", "district_id"=>"17", "is_active"=>"1", "name_bn"=>"জয়পুরহাট সদর"),
            array("name"=>"Chapainawabganj Sadar", "district_id"=>"18", "is_active"=>"1", "name_bn"=>"চাঁপাইনবাবগঞ্জ সদর"),
            array("name"=>"Gomostapur", "district_id"=>"18", "is_active"=>"1", "name_bn"=>"গোমস্তাপুর"),
            array("name"=>"Nachol", "district_id"=>"18", "is_active"=>"1", "name_bn"=>"নাচোল"),
            array("name"=>"Bholahat", "district_id"=>"18", "is_active"=>"1", "name_bn"=>"ভোলাহাট"),
            array("name"=>"Shibganj", "district_id"=>"18", "is_active"=>"1", "name_bn"=>"শিবগঞ্জ"),
            array("name"=>"Mohadevpur", "district_id"=>"19", "is_active"=>"1", "name_bn"=>"মহাদেবপুর"),
            array("name"=>"Badalgachi", "district_id"=>"19", "is_active"=>"1", "name_bn"=>"বদলগাছী"),
            array("name"=>"Patnitala", "district_id"=>"19", "is_active"=>"1", "name_bn"=>"পত্নিতলা"),
            array("name"=>"Dhamoirhat", "district_id"=>"19", "is_active"=>"1", "name_bn"=>"ধামইরহাট"),
            array("name"=>"Niamatpur", "district_id"=>"19", "is_active"=>"1", "name_bn"=>"নিয়ামতপুর"),
            array("name"=>"Manda", "district_id"=>"19", "is_active"=>"1", "name_bn"=>"মান্দা"),
            array("name"=>"Atrai", "district_id"=>"19", "is_active"=>"1", "name_bn"=>"আত্রাই"),
            array("name"=>"Raninagar", "district_id"=>"19", "is_active"=>"1", "name_bn"=>"রাণীনগর"),
            array("name"=>"Naogaon Sadar", "district_id"=>"19", "is_active"=>"1", "name_bn"=>"নওগাঁ সদর"),
            array("name"=>"Porsha", "district_id"=>"19", "is_active"=>"1", "name_bn"=>"পোরশা"),
            array("name"=>"Sapahar", "district_id"=>"19", "is_active"=>"1", "name_bn"=>"সাপাহার"),
            array("name"=>"Manirampur", "district_id"=>"20", "is_active"=>"1", "name_bn"=>"মণিরামপুর"),
            array("name"=>"Abhaynagar", "district_id"=>"20", "is_active"=>"1", "name_bn"=>"অভয়নগর"),
            array("name"=>"Bagherpara", "district_id"=>"20", "is_active"=>"1", "name_bn"=>"বাঘারপাড়া"),
            array("name"=>"Chougachha", "district_id"=>"20", "is_active"=>"1", "name_bn"=>"চৌগাছা"),
            array("name"=>"Jhikargacha", "district_id"=>"20", "is_active"=>"1", "name_bn"=>"ঝিকরগাছা"),
            array("name"=>"Keshabpur", "district_id"=>"20", "is_active"=>"1", "name_bn"=>"কেশবপুর"),
            array("name"=>"Jessore Sadar", "district_id"=>"20", "is_active"=>"1", "name_bn"=>"যশোর সদর"),
            array("name"=>"Sharsha", "district_id"=>"20", "is_active"=>"1", "name_bn"=>"শার্শা"),
            array("name"=>"Assasuni", "district_id"=>"21", "is_active"=>"1", "name_bn"=>"আশাশুনি"),
            array("name"=>"Debhata", "district_id"=>"21", "is_active"=>"1", "name_bn"=>"দেবহাটা"),
            array("name"=>"Kalaroa", "district_id"=>"21", "is_active"=>"1", "name_bn"=>"কলারোয়া"),
            array("name"=>"Satkhira Sadar", "district_id"=>"21", "is_active"=>"1", "name_bn"=>"সাতক্ষীরা সদর"),
            array("name"=>"Shyamnagar", "district_id"=>"21", "is_active"=>"1", "name_bn"=>"শ্যামনগর"),
            array("name"=>"Tala", "district_id"=>"21", "is_active"=>"1", "name_bn"=>"তালা"),
            array("name"=>"Kaliganj", "district_id"=>"21", "is_active"=>"1", "name_bn"=>"কালিগঞ্জ"),
            array("name"=>"Mujibnagar", "district_id"=>"22", "is_active"=>"1", "name_bn"=>"মুজিবনগর"),
            array("name"=>"Meherpur Sadar", "district_id"=>"22", "is_active"=>"1", "name_bn"=>"মেহেরপুর সদর"),
            array("name"=>"Gangni", "district_id"=>"22", "is_active"=>"1", "name_bn"=>"গাংনী"),
            array("name"=>"Narail Sadar", "district_id"=>"23", "is_active"=>"1", "name_bn"=>"নড়াইল সদর"),
            array("name"=>"Lohagara", "district_id"=>"23", "is_active"=>"1", "name_bn"=>"লোহাগড়া"),
            array("name"=>"Kalia", "district_id"=>"23", "is_active"=>"1", "name_bn"=>"কালিয়া"),
            array("name"=>"Chuadanga Sadar", "district_id"=>"24", "is_active"=>"1", "name_bn"=>"চুয়াডাঙ্গা সদর"),
            array("name"=>"Alamdanga", "district_id"=>"24", "is_active"=>"1", "name_bn"=>"আলমডাঙ্গা"),
            array("name"=>"Damurhuda", "district_id"=>"24", "is_active"=>"1", "name_bn"=>"দামুড়হুদা"),
            array("name"=>"Jibannagar", "district_id"=>"24", "is_active"=>"1", "name_bn"=>"জীবননগর"),
            array("name"=>"Kushtia Sadar", "district_id"=>"25", "is_active"=>"1", "name_bn"=>"কুষ্টিয়া সদর"),
            array("name"=>"Kumarkhali", "district_id"=>"25", "is_active"=>"1", "name_bn"=>"কুমারখালী"),
            array("name"=>"Khoksa", "district_id"=>"25", "is_active"=>"1", "name_bn"=>"খোকসা"),
            array("name"=>"Mirpur", "district_id"=>"25", "is_active"=>"1", "name_bn"=>"মিরপুর"),
            array("name"=>"Daulatpur", "district_id"=>"25", "is_active"=>"1", "name_bn"=>"দৌলতপুর"),
            array("name"=>"Bheramara", "district_id"=>"25", "is_active"=>"1", "name_bn"=>"ভেড়ামারা"),
            array("name"=>"Shalikha", "district_id"=>"26", "is_active"=>"1", "name_bn"=>"শালিখা"),
            array("name"=>"Sreepur", "district_id"=>"26", "is_active"=>"1", "name_bn"=>"শ্রীপুর"),
            array("name"=>"Magura Sadar", "district_id"=>"26", "is_active"=>"1", "name_bn"=>"মাগুরা সদর"),
            array("name"=>"Mohammadpur", "district_id"=>"26", "is_active"=>"1", "name_bn"=>"মহম্মদপুর"),
            array("name"=>"Paikgasa", "district_id"=>"27", "is_active"=>"1", "name_bn"=>"পাইকগাছা"),
            array("name"=>"Fultola", "district_id"=>"27", "is_active"=>"1", "name_bn"=>"ফুলতলা"),
            array("name"=>"Digholia", "district_id"=>"27", "is_active"=>"1", "name_bn"=>"দিঘলিয়া"),
            array("name"=>"Rupsha", "district_id"=>"27", "is_active"=>"1", "name_bn"=>"রূপসা"),
            array("name"=>"Terokhada", "district_id"=>"27", "is_active"=>"1", "name_bn"=>"তেরখাদা"),
            array("name"=>"Dumuria", "district_id"=>"27", "is_active"=>"1", "name_bn"=>"ডুমুরিয়া"),
            array("name"=>"Botiaghata", "district_id"=>"27", "is_active"=>"1", "name_bn"=>"বটিয়াঘাটা"),
            array("name"=>"Dakop", "district_id"=>"27", "is_active"=>"1", "name_bn"=>"দাকোপ"),
            array("name"=>"Koyra", "district_id"=>"27", "is_active"=>"1", "name_bn"=>"কয়রা"),
            array("name"=>"Fakirhat", "district_id"=>"28", "is_active"=>"1", "name_bn"=>"ফকিরহাট"),
            array("name"=>"Bagerhat Sadar", "district_id"=>"28", "is_active"=>"1", "name_bn"=>"বাগেরহাট সদর"),
            array("name"=>"Mollahat", "district_id"=>"28", "is_active"=>"1", "name_bn"=>"মোল্লাহাট"),
            array("name"=>"Sarankhola", "district_id"=>"28", "is_active"=>"1", "name_bn"=>"শরণখোলা"),
            array("name"=>"Rampal", "district_id"=>"28", "is_active"=>"1", "name_bn"=>"রামপাল"),
            array("name"=>"Morrelganj", "district_id"=>"28", "is_active"=>"1", "name_bn"=>"মোড়েলগঞ্জ"),
            array("name"=>"Kachua", "district_id"=>"28", "is_active"=>"1", "name_bn"=>"কচুয়া"),
            array("name"=>"Mongla", "district_id"=>"28", "is_active"=>"1", "name_bn"=>"মোংলা"),
            array("name"=>"Chitalmari", "district_id"=>"28", "is_active"=>"1", "name_bn"=>"চিতলমারী"),
            array("name"=>"Jhenaidah Sadar", "district_id"=>"29", "is_active"=>"1", "name_bn"=>"ঝিনাইদহ সদর"),
            array("name"=>"Shailkupa", "district_id"=>"29", "is_active"=>"1", "name_bn"=>"শৈলকুপা"),
            array("name"=>"Harinakundu", "district_id"=>"29", "is_active"=>"1", "name_bn"=>"হরিণাকুন্ডু"),
            array("name"=>"Kaliganj", "district_id"=>"29", "is_active"=>"1", "name_bn"=>"কালীগঞ্জ"),
            array("name"=>"Kotchandpur", "district_id"=>"29", "is_active"=>"1", "name_bn"=>"কোটচাঁদপুর"),
            array("name"=>"Moheshpur", "district_id"=>"29", "is_active"=>"1", "name_bn"=>"মহেশপুর"),
            array("name"=>"Jhalakathi Sadar", "district_id"=>"30", "is_active"=>"1", "name_bn"=>"ঝালকাঠি সদর"),
            array("name"=>"Kathalia", "district_id"=>"30", "is_active"=>"1", "name_bn"=>"কাঠালিয়া"),
            array("name"=>"Nalchity", "district_id"=>"30", "is_active"=>"1", "name_bn"=>"নলছিটি"),
            array("name"=>"Rajapur", "district_id"=>"30", "is_active"=>"1", "name_bn"=>"রাজাপুর"),
            array("name"=>"Bauphal", "district_id"=>"31", "is_active"=>"1", "name_bn"=>"বাউফল"),
            array("name"=>"Patuakhali Sadar", "district_id"=>"31", "is_active"=>"1", "name_bn"=>"পটুয়াখালী সদর"),
            array("name"=>"Dumki", "district_id"=>"31", "is_active"=>"1", "name_bn"=>"দুমকি"),
            array("name"=>"Dashmina", "district_id"=>"31", "is_active"=>"1", "name_bn"=>"দশমিনা"),
            array("name"=>"Kalapara", "district_id"=>"31", "is_active"=>"1", "name_bn"=>"কলাপাড়া"),
            array("name"=>"Mirzaganj", "district_id"=>"31", "is_active"=>"1", "name_bn"=>"মির্জাগঞ্জ"),
            array("name"=>"Galachipa", "district_id"=>"31", "is_active"=>"1", "name_bn"=>"গলাচিপা"),
            array("name"=>"Rangabali", "district_id"=>"31", "is_active"=>"1", "name_bn"=>"রাঙ্গাবালী"),
            array("name"=>"Pirojpur Sadar", "district_id"=>"32", "is_active"=>"1", "name_bn"=>"পিরোজপুর সদর"),
            array("name"=>"Nazirpur", "district_id"=>"32", "is_active"=>"1", "name_bn"=>"নাজিরপুর"),
            array("name"=>"Kawkhali", "district_id"=>"32", "is_active"=>"1", "name_bn"=>"কাউখালী"),
            array("name"=>"Zianagar", "district_id"=>"32", "is_active"=>"1", "name_bn"=>"জিয়ানগর"),
            array("name"=>"Bhandaria", "district_id"=>"32", "is_active"=>"1", "name_bn"=>"ভান্ডারিয়া"),
            array("name"=>"Mathbaria", "district_id"=>"32", "is_active"=>"1", "name_bn"=>"মঠবাড়ীয়া"),
            array("name"=>"Nesarabad", "district_id"=>"32", "is_active"=>"1", "name_bn"=>"নেছারাবাদ"),
            array("name"=>"Barisal Sadar", "district_id"=>"33", "is_active"=>"1", "name_bn"=>"বরিশাল সদর"),
            array("name"=>"Bakerganj", "district_id"=>"33", "is_active"=>"1", "name_bn"=>"বাকেরগঞ্জ"),
            array("name"=>"Babuganj", "district_id"=>"33", "is_active"=>"1", "name_bn"=>"বাবুগঞ্জ"),
            array("name"=>"Wazirpur", "district_id"=>"33", "is_active"=>"1", "name_bn"=>"উজিরপুর"),
            array("name"=>"Banaripara", "district_id"=>"33", "is_active"=>"1", "name_bn"=>"বানারীপাড়া"),
            array("name"=>"Gournadi", "district_id"=>"33", "is_active"=>"1", "name_bn"=>"গৌরনদী"),
            array("name"=>"Agailjhara", "district_id"=>"33", "is_active"=>"1", "name_bn"=>"আগৈলঝাড়া"),
            array("name"=>"Mehendiganj", "district_id"=>"33", "is_active"=>"1", "name_bn"=>"মেহেন্দিগঞ্জ"),
            array("name"=>"Muladi", "district_id"=>"33", "is_active"=>"1", "name_bn"=>"মুলাদী"),
            array("name"=>"Hizla", "district_id"=>"33", "is_active"=>"1", "name_bn"=>"হিজলা"),
            array("name"=>"Bhola Sadar", "district_id"=>"34", "is_active"=>"1", "name_bn"=>"ভোলা সদর"),
            array("name"=>"Borhan Sddin", "district_id"=>"34", "is_active"=>"1", "name_bn"=>"বোরহান উদ্দিন"),
            array("name"=>"Charfesson", "district_id"=>"34", "is_active"=>"1", "name_bn"=>"চরফ্যাশন"),
            array("name"=>"Doulatkhan", "district_id"=>"34", "is_active"=>"1", "name_bn"=>"দৌলতখান"),
            array("name"=>"Monpura", "district_id"=>"34", "is_active"=>"1", "name_bn"=>"মনপুরা"),
            array("name"=>"Tazumuddin", "district_id"=>"34", "is_active"=>"1", "name_bn"=>"তজুমদ্দিন"),
            array("name"=>"Lalmohan", "district_id"=>"34", "is_active"=>"1", "name_bn"=>"লালমোহন"),
            array("name"=>"Amtali", "district_id"=>"35", "is_active"=>"1", "name_bn"=>"আমতলী"),
            array("name"=>"Barguna Sadar", "district_id"=>"35", "is_active"=>"1", "name_bn"=>"বরগুনা সদর"),
            array("name"=>"Betagi", "district_id"=>"35", "is_active"=>"1", "name_bn"=>"বেতাগী"),
            array("name"=>"Bamna", "district_id"=>"35", "is_active"=>"1", "name_bn"=>"বামনা"),
            array("name"=>"Pathorghata", "district_id"=>"35", "is_active"=>"1", "name_bn"=>"পাথরঘাটা"),
            array("name"=>"Taltali", "district_id"=>"35", "is_active"=>"1", "name_bn"=>"তালতলি"),
            array("name"=>"Balaganj", "district_id"=>"36", "is_active"=>"1", "name_bn"=>"বালাগঞ্জ"),
            array("name"=>"Beanibazar", "district_id"=>"36", "is_active"=>"1", "name_bn"=>"বিয়ানীবাজার"),
            array("name"=>"Bishwanath", "district_id"=>"36", "is_active"=>"1", "name_bn"=>"বিশ্বনাথ"),
            array("name"=>"Companiganj", "district_id"=>"36", "is_active"=>"1", "name_bn"=>"কোম্পানীগঞ্জ"),
            array("name"=>"Fenchuganj", "district_id"=>"36", "is_active"=>"1", "name_bn"=>"ফেঞ্চুগঞ্জ"),
            array("name"=>"Golapganj", "district_id"=>"36", "is_active"=>"1", "name_bn"=>"গোলাপগঞ্জ"),
            array("name"=>"Gowainghat", "district_id"=>"36", "is_active"=>"1", "name_bn"=>"গোয়াইনঘাট"),
            array("name"=>"Jaintiapur", "district_id"=>"36", "is_active"=>"1", "name_bn"=>"জৈন্তাপুর"),
            array("name"=>"Kanaighat", "district_id"=>"36", "is_active"=>"1", "name_bn"=>"কানাইঘাট"),
            array("name"=>"Sylhet Sadar", "district_id"=>"36", "is_active"=>"1", "name_bn"=>"সিলেট সদর"),
            array("name"=>"Zakiganj", "district_id"=>"36", "is_active"=>"1", "name_bn"=>"জকিগঞ্জ"),
            array("name"=>"Dakshinsurma", "district_id"=>"36", "is_active"=>"1", "name_bn"=>"দক্ষিণ সুরমা"),
            array("name"=>"Osmaninagar", "district_id"=>"36", "is_active"=>"1", "name_bn"=>"ওসমানী নগর"),
            array("name"=>"Barlekha", "district_id"=>"37", "is_active"=>"1", "name_bn"=>"বড়লেখা"),
            array("name"=>"Kamolganj", "district_id"=>"37", "is_active"=>"1", "name_bn"=>"কমলগঞ্জ"),
            array("name"=>"Kulaura", "district_id"=>"37", "is_active"=>"1", "name_bn"=>"কুলাউড়া"),
            array("name"=>"Moulvibazar Sadar", "district_id"=>"37", "is_active"=>"1", "name_bn"=>"মৌলভীবাজার সদর"),
            array("name"=>"Rajnagar", "district_id"=>"37", "is_active"=>"1", "name_bn"=>"রাজনগর"),
            array("name"=>"Sreemangal", "district_id"=>"37", "is_active"=>"1", "name_bn"=>"শ্রীমঙ্গল"),
            array("name"=>"Juri", "district_id"=>"37", "is_active"=>"1", "name_bn"=>"জুড়ী"),
            array("name"=>"Nabiganj", "district_id"=>"38", "is_active"=>"1", "name_bn"=>"নবীগঞ্জ"),
            array("name"=>"Bahubal", "district_id"=>"38", "is_active"=>"1", "name_bn"=>"বাহুবল"),
            array("name"=>"Ajmiriganj", "district_id"=>"38", "is_active"=>"1", "name_bn"=>"আজমিরীগঞ্জ"),
            array("name"=>"Baniachong", "district_id"=>"38", "is_active"=>"1", "name_bn"=>"বানিয়াচং"),
            array("name"=>"Lakhai", "district_id"=>"38", "is_active"=>"1", "name_bn"=>"লাখাই"),
            array("name"=>"Chunarughat", "district_id"=>"38", "is_active"=>"1", "name_bn"=>"চুনারুঘাট"),
            array("name"=>"Habiganj Sadar", "district_id"=>"38", "is_active"=>"1", "name_bn"=>"হবিগঞ্জ সদর"),
            array("name"=>"Madhabpur", "district_id"=>"38", "is_active"=>"1", "name_bn"=>"মাধবপুর"),
            array("name"=>"Sunamganj Sadar", "district_id"=>"39", "is_active"=>"1", "name_bn"=>"সুনামগঞ্জ সদর"),
            array("name"=>"South Sunamganj", "district_id"=>"39", "is_active"=>"1", "name_bn"=>"দক্ষিণ সুনামগঞ্জ"),
            array("name"=>"Bishwambarpur", "district_id"=>"39", "is_active"=>"1", "name_bn"=>"বিশ্বম্ভরপুর"),
            array("name"=>"Chhatak", "district_id"=>"39", "is_active"=>"1", "name_bn"=>"ছাতক"),
            array("name"=>"Jagannathpur", "district_id"=>"39", "is_active"=>"1", "name_bn"=>"জগন্নাথপুর"),
            array("name"=>"Dowarabazar", "district_id"=>"39", "is_active"=>"1", "name_bn"=>"দোয়ারাবাজার"),
            array("name"=>"Tahirpur", "district_id"=>"39", "is_active"=>"1", "name_bn"=>"তাহিরপুর"),
            array("name"=>"Dharmapasha", "district_id"=>"39", "is_active"=>"1", "name_bn"=>"ধর্মপাশা"),
            array("name"=>"Jamalganj", "district_id"=>"39", "is_active"=>"1", "name_bn"=>"জামালগঞ্জ"),
            array("name"=>"Shalla", "district_id"=>"39", "is_active"=>"1", "name_bn"=>"শাল্লা"),
            array("name"=>"Derai", "district_id"=>"39", "is_active"=>"1", "name_bn"=>"দিরাই"),
            array("name"=>"Belabo", "district_id"=>"40", "is_active"=>"1", "name_bn"=>"বেলাবো"),
            array("name"=>"Monohardi", "district_id"=>"40", "is_active"=>"1", "name_bn"=>"মনোহরদী"),
            array("name"=>"Narsingdi Sadar", "district_id"=>"40", "is_active"=>"1", "name_bn"=>"নরসিংদী সদর"),
            array("name"=>"Palash", "district_id"=>"40", "is_active"=>"1", "name_bn"=>"পলাশ"),
            array("name"=>"Raipura", "district_id"=>"40", "is_active"=>"1", "name_bn"=>"রায়পুরা"),
            array("name"=>"Shibpur", "district_id"=>"40", "is_active"=>"1", "name_bn"=>"শিবপুর"),
            array("name"=>"Kaliganj", "district_id"=>"41", "is_active"=>"1", "name_bn"=>"কালীগঞ্জ"),
            array("name"=>"Kaliakair", "district_id"=>"41", "is_active"=>"1", "name_bn"=>"কালিয়াকৈর"),
            array("name"=>"Kapasia", "district_id"=>"41", "is_active"=>"1", "name_bn"=>"কাপাসিয়া"),
            array("name"=>"Gazipur Sadar", "district_id"=>"41", "is_active"=>"1", "name_bn"=>"গাজীপুর সদর"),
            array("name"=>"Sreepur", "district_id"=>"41", "is_active"=>"1", "name_bn"=>"শ্রীপুর"),
            array("name"=>"Shariatpur Sadar", "district_id"=>"42", "is_active"=>"1", "name_bn"=>"শরিয়তপুর সদর"),
            array("name"=>"Naria", "district_id"=>"42", "is_active"=>"1", "name_bn"=>"নড়িয়া"),
            array("name"=>"Zajira", "district_id"=>"42", "is_active"=>"1", "name_bn"=>"জাজিরা"),
            array("name"=>"Gosairhat", "district_id"=>"42", "is_active"=>"1", "name_bn"=>"গোসাইরহাট"),
            array("name"=>"Bhedarganj", "district_id"=>"42", "is_active"=>"1", "name_bn"=>"ভেদরগঞ্জ"),
            array("name"=>"Damudya", "district_id"=>"42", "is_active"=>"1", "name_bn"=>"ডামুড্যা"),
            array("name"=>"Araihazar", "district_id"=>"43", "is_active"=>"1", "name_bn"=>"আড়াইহাজার"),
            array("name"=>"Bandar", "district_id"=>"43", "is_active"=>"1", "name_bn"=>"বন্দর"),
            array("name"=>"Narayanganj Sadar", "district_id"=>"43", "is_active"=>"1", "name_bn"=>"নারায়নগঞ্জ সদর"),
            array("name"=>"Rupganj", "district_id"=>"43", "is_active"=>"1", "name_bn"=>"রূপগঞ্জ"),
            array("name"=>"Sonargaon", "district_id"=>"43", "is_active"=>"1", "name_bn"=>"সোনারগাঁ"),
            array("name"=>"Basail", "district_id"=>"44", "is_active"=>"1", "name_bn"=>"বাসাইল"),
            array("name"=>"Bhuapur", "district_id"=>"44", "is_active"=>"1", "name_bn"=>"ভুয়াপুর"),
            array("name"=>"Delduar", "district_id"=>"44", "is_active"=>"1", "name_bn"=>"দেলদুয়ার"),
            array("name"=>"Ghatail", "district_id"=>"44", "is_active"=>"1", "name_bn"=>"ঘাটাইল"),
            array("name"=>"Gopalpur", "district_id"=>"44", "is_active"=>"1", "name_bn"=>"গোপালপুর"),
            array("name"=>"Madhupur", "district_id"=>"44", "is_active"=>"1", "name_bn"=>"মধুপুর"),
            array("name"=>"Mirzapur", "district_id"=>"44", "is_active"=>"1", "name_bn"=>"মির্জাপুর"),
            array("name"=>"Nagarpur", "district_id"=>"44", "is_active"=>"1", "name_bn"=>"নাগরপুর"),
            array("name"=>"Sakhipur", "district_id"=>"44", "is_active"=>"1", "name_bn"=>"সখিপুর"),
            array("name"=>"Tangail Sadar", "district_id"=>"44", "is_active"=>"1", "name_bn"=>"টাঙ্গাইল সদর"),
            array("name"=>"Kalihati", "district_id"=>"44", "is_active"=>"1", "name_bn"=>"কালিহাতী"),
            array("name"=>"Dhanbari", "district_id"=>"44", "is_active"=>"1", "name_bn"=>"ধনবাড়ী"),
            array("name"=>"Itna", "district_id"=>"45", "is_active"=>"1", "name_bn"=>"ইটনা"),
            array("name"=>"Katiadi", "district_id"=>"45", "is_active"=>"1", "name_bn"=>"কটিয়াদী"),
            array("name"=>"Bhairab", "district_id"=>"45", "is_active"=>"1", "name_bn"=>"ভৈরব"),
            array("name"=>"Tarail", "district_id"=>"45", "is_active"=>"1", "name_bn"=>"তাড়াইল"),
            array("name"=>"Hossainpur", "district_id"=>"45", "is_active"=>"1", "name_bn"=>"হোসেনপুর"),
            array("name"=>"Pakundia", "district_id"=>"45", "is_active"=>"1", "name_bn"=>"পাকুন্দিয়া"),
            array("name"=>"Kuliarchar", "district_id"=>"45", "is_active"=>"1", "name_bn"=>"কুলিয়ারচর"),
            array("name"=>"Kishoreganj Sadar", "district_id"=>"45", "is_active"=>"1", "name_bn"=>"কিশোরগঞ্জ সদর"),
            array("name"=>"Karimgonj", "district_id"=>"45", "is_active"=>"1", "name_bn"=>"করিমগঞ্জ"),
            array("name"=>"Bajitpur", "district_id"=>"45", "is_active"=>"1", "name_bn"=>"বাজিতপুর"),
            array("name"=>"Austagram", "district_id"=>"45", "is_active"=>"1", "name_bn"=>"অষ্টগ্রাম"),
            array("name"=>"Mithamoin", "district_id"=>"45", "is_active"=>"1", "name_bn"=>"মিঠামইন"),
            array("name"=>"Nikli", "district_id"=>"45", "is_active"=>"1", "name_bn"=>"নিকলী"),
            array("name"=>"Harirampur", "district_id"=>"46", "is_active"=>"1", "name_bn"=>"হরিরামপুর"),
            array("name"=>"Saturia", "district_id"=>"46", "is_active"=>"1", "name_bn"=>"সাটুরিয়া"),
            array("name"=>"Manikganj Sadar", "district_id"=>"46", "is_active"=>"1", "name_bn"=>"মানিকগঞ্জ সদর"),
            array("name"=>"Gior", "district_id"=>"46", "is_active"=>"1", "name_bn"=>"ঘিওর"),
            array("name"=>"Shibaloy", "district_id"=>"46", "is_active"=>"1", "name_bn"=>"শিবালয়"),
            array("name"=>"Doulatpur", "district_id"=>"46", "is_active"=>"1", "name_bn"=>"দৌলতপুর"),
            array("name"=>"Singiar", "district_id"=>"46", "is_active"=>"1", "name_bn"=>"সিংগাইর"),
            array("name"=>"Savar", "district_id"=>"47", "is_active"=>"1", "name_bn"=>"সাভার"),
            array("name"=>"Dhamrai", "district_id"=>"47", "is_active"=>"1", "name_bn"=>"ধামরাই"),
            array("name"=>"Keraniganj", "district_id"=>"47", "is_active"=>"1", "name_bn"=>"কেরাণীগঞ্জ"),
            array("name"=>"Nawabganj", "district_id"=>"47", "is_active"=>"1", "name_bn"=>"নবাবগঞ্জ"),
            array("name"=>"Dohar", "district_id"=>"47", "is_active"=>"1", "name_bn"=>"দোহার"),
            array("name"=>"Munshiganj Sadar", "district_id"=>"48", "is_active"=>"1", "name_bn"=>"মুন্সিগঞ্জ সদর"),
            array("name"=>"Sreenagar", "district_id"=>"48", "is_active"=>"1", "name_bn"=>"শ্রীনগর"),
            array("name"=>"Sirajdikhan", "district_id"=>"48", "is_active"=>"1", "name_bn"=>"সিরাজদিখান"),
            array("name"=>"Louhajanj", "district_id"=>"48", "is_active"=>"1", "name_bn"=>"লৌহজং"),
            array("name"=>"Gajaria", "district_id"=>"48", "is_active"=>"1", "name_bn"=>"গজারিয়া"),
            array("name"=>"Tongibari", "district_id"=>"48", "is_active"=>"1", "name_bn"=>"টংগীবাড়ি"),
            array("name"=>"Rajbari Sadar", "district_id"=>"49", "is_active"=>"1", "name_bn"=>"রাজবাড়ী সদর"),
            array("name"=>"Goalanda", "district_id"=>"49", "is_active"=>"1", "name_bn"=>"গোয়ালন্দ"),
            array("name"=>"Pangsa", "district_id"=>"49", "is_active"=>"1", "name_bn"=>"পাংশা"),
            array("name"=>"Baliakandi", "district_id"=>"49", "is_active"=>"1", "name_bn"=>"বালিয়াকান্দি"),
            array("name"=>"Kalukhali", "district_id"=>"49", "is_active"=>"1", "name_bn"=>"কালুখালী"),
            array("name"=>"Madaripur Sadar", "district_id"=>"50", "is_active"=>"1", "name_bn"=>"মাদারীপুর সদর"),
            array("name"=>"Shibchar", "district_id"=>"50", "is_active"=>"1", "name_bn"=>"শিবচর"),
            array("name"=>"Kalkini", "district_id"=>"50", "is_active"=>"1", "name_bn"=>"কালকিনি"),
            array("name"=>"Rajoir", "district_id"=>"50", "is_active"=>"1", "name_bn"=>"রাজৈর"),
            array("name"=>"Gopalganj Sadar", "district_id"=>"51", "is_active"=>"1", "name_bn"=>"গোপালগঞ্জ সদর"),
            array("name"=>"Kashiani", "district_id"=>"51", "is_active"=>"1", "name_bn"=>"কাশিয়ানী"),
            array("name"=>"Tungipara", "district_id"=>"51", "is_active"=>"1", "name_bn"=>"টুংগীপাড়া"),
            array("name"=>"Kotalipara", "district_id"=>"51", "is_active"=>"1", "name_bn"=>"কোটালীপাড়া"),
            array("name"=>"Muksudpur", "district_id"=>"51", "is_active"=>"1", "name_bn"=>"মুকসুদপুর"),
            array("name"=>"Faridpur Sadar", "district_id"=>"52", "is_active"=>"1", "name_bn"=>"ফরিদপুর সদর"),
            array("name"=>"Alfadanga", "district_id"=>"52", "is_active"=>"1", "name_bn"=>"আলফাডাঙ্গা"),
            array("name"=>"Boalmari", "district_id"=>"52", "is_active"=>"1", "name_bn"=>"বোয়ালমারী"),
            array("name"=>"Sadarpur", "district_id"=>"52", "is_active"=>"1", "name_bn"=>"সদরপুর"),
            array("name"=>"Nagarkanda", "district_id"=>"52", "is_active"=>"1", "name_bn"=>"নগরকান্দা"),
            array("name"=>"Bhanga", "district_id"=>"52", "is_active"=>"1", "name_bn"=>"ভাঙ্গা"),
            array("name"=>"Charbhadrasan", "district_id"=>"52", "is_active"=>"1", "name_bn"=>"চরভদ্রাসন"),
            array("name"=>"Madhukhali", "district_id"=>"52", "is_active"=>"1", "name_bn"=>"মধুখালী"),
            array("name"=>"Saltha", "district_id"=>"52", "is_active"=>"1", "name_bn"=>"সালথা"),
            array("name"=>"Panchagarh Sadar", "district_id"=>"53", "is_active"=>"1", "name_bn"=>"পঞ্চগড় সদর"),
            array("name"=>"Debiganj", "district_id"=>"53", "is_active"=>"1", "name_bn"=>"দেবীগঞ্জ"),
            array("name"=>"Boda", "district_id"=>"53", "is_active"=>"1", "name_bn"=>"বোদা"),
            array("name"=>"Atwari", "district_id"=>"53", "is_active"=>"1", "name_bn"=>"আটোয়ারী"),
            array("name"=>"Tetulia", "district_id"=>"53", "is_active"=>"1", "name_bn"=>"তেতুলিয়া"),
            array("name"=>"Nawabganj", "district_id"=>"54", "is_active"=>"1", "name_bn"=>"নবাবগঞ্জ"),
            array("name"=>"Birganj", "district_id"=>"54", "is_active"=>"1", "name_bn"=>"বীরগঞ্জ"),
            array("name"=>"Ghoraghat", "district_id"=>"54", "is_active"=>"1", "name_bn"=>"ঘোড়াঘাট"),
            array("name"=>"Birampur", "district_id"=>"54", "is_active"=>"1", "name_bn"=>"বিরামপুর"),
            array("name"=>"Parbatipur", "district_id"=>"54", "is_active"=>"1", "name_bn"=>"পার্বতীপুর"),
            array("name"=>"Bochaganj", "district_id"=>"54", "is_active"=>"1", "name_bn"=>"বোচাগঞ্জ"),
            array("name"=>"Kaharol", "district_id"=>"54", "is_active"=>"1", "name_bn"=>"কাহারোল"),
            array("name"=>"Fulbari", "district_id"=>"54", "is_active"=>"1", "name_bn"=>"ফুলবাড়ী"),
            array("name"=>"Dinajpur Sadar", "district_id"=>"54", "is_active"=>"1", "name_bn"=>"দিনাজপুর সদর"),
            array("name"=>"Hakimpur", "district_id"=>"54", "is_active"=>"1", "name_bn"=>"হাকিমপুর"),
            array("name"=>"Khansama", "district_id"=>"54", "is_active"=>"1", "name_bn"=>"খানসামা"),
            array("name"=>"Birol", "district_id"=>"54", "is_active"=>"1", "name_bn"=>"বিরল"),
            array("name"=>"Chirirbandar", "district_id"=>"54", "is_active"=>"1", "name_bn"=>"চিরিরবন্দর"),
            array("name"=>"Lalmonirhat Sadar", "district_id"=>"55", "is_active"=>"1", "name_bn"=>"লালমনিরহাট সদর"),
            array("name"=>"Kaliganj", "district_id"=>"55", "is_active"=>"1", "name_bn"=>"কালীগঞ্জ"),
            array("name"=>"Hatibandha", "district_id"=>"55", "is_active"=>"1", "name_bn"=>"হাতীবান্ধা"),
            array("name"=>"Patgram", "district_id"=>"55", "is_active"=>"1", "name_bn"=>"পাটগ্রাম"),
            array("name"=>"Aditmari", "district_id"=>"55", "is_active"=>"1", "name_bn"=>"আদিতমারী"),
            array("name"=>"Syedpur", "district_id"=>"56", "is_active"=>"1", "name_bn"=>"সৈয়দপুর"),
            array("name"=>"Domar", "district_id"=>"56", "is_active"=>"1", "name_bn"=>"ডোমার"),
            array("name"=>"Dimla", "district_id"=>"56", "is_active"=>"1", "name_bn"=>"ডিমলা"),
            array("name"=>"Jaldhaka", "district_id"=>"56", "is_active"=>"1", "name_bn"=>"জলঢাকা"),
            array("name"=>"Kishorganj", "district_id"=>"56", "is_active"=>"1", "name_bn"=>"কিশোরগঞ্জ"),
            array("name"=>"Nilphamari Sadar", "district_id"=>"56", "is_active"=>"1", "name_bn"=>"নীলফামারী সদর"),
            array("name"=>"Sadullapur", "district_id"=>"57", "is_active"=>"1", "name_bn"=>"সাদুল্লাপুর"),
            array("name"=>"Gaibandha Sadar", "district_id"=>"57", "is_active"=>"1", "name_bn"=>"গাইবান্ধা সদর"),
            array("name"=>"Palashbari", "district_id"=>"57", "is_active"=>"1", "name_bn"=>"পলাশবাড়ী"),
            array("name"=>"Saghata", "district_id"=>"57", "is_active"=>"1", "name_bn"=>"সাঘাটা"),
            array("name"=>"Gobindaganj", "district_id"=>"57", "is_active"=>"1", "name_bn"=>"গোবিন্দগঞ্জ"),
            array("name"=>"Sundarganj", "district_id"=>"57", "is_active"=>"1", "name_bn"=>"সুন্দরগঞ্জ"),
            array("name"=>"Phulchari", "district_id"=>"57", "is_active"=>"1", "name_bn"=>"ফুলছড়ি"),
            array("name"=>"Thakurgaon Sadar", "district_id"=>"58", "is_active"=>"1", "name_bn"=>"ঠাকুরগাঁও সদর"),
            array("name"=>"Pirganj", "district_id"=>"58", "is_active"=>"1", "name_bn"=>"পীরগঞ্জ"),
            array("name"=>"Ranisankail", "district_id"=>"58", "is_active"=>"1", "name_bn"=>"রাণীশংকৈল"),
            array("name"=>"Haripur", "district_id"=>"58", "is_active"=>"1", "name_bn"=>"হরিপুর"),
            array("name"=>"Baliadangi", "district_id"=>"58", "is_active"=>"1", "name_bn"=>"বালিয়াডাঙ্গী"),
            array("name"=>"Rangpur Sadar", "district_id"=>"59", "is_active"=>"1", "name_bn"=>"রংপুর সদর"),
            array("name"=>"Gangachara", "district_id"=>"59", "is_active"=>"1", "name_bn"=>"গংগাচড়া"),
            array("name"=>"Taragonj", "district_id"=>"59", "is_active"=>"1", "name_bn"=>"তারাগঞ্জ"),
            array("name"=>"Badargonj", "district_id"=>"59", "is_active"=>"1", "name_bn"=>"বদরগঞ্জ"),
            array("name"=>"Mithapukur", "district_id"=>"59", "is_active"=>"1", "name_bn"=>"মিঠাপুকুর"),
            array("name"=>"Pirgonj", "district_id"=>"59", "is_active"=>"1", "name_bn"=>"পীরগঞ্জ"),
            array("name"=>"Kaunia", "district_id"=>"59", "is_active"=>"1", "name_bn"=>"কাউনিয়া"),
            array("name"=>"Pirgacha", "district_id"=>"59", "is_active"=>"1", "name_bn"=>"পীরগাছা"),
            array("name"=>"Kurigram Sadar", "district_id"=>"60", "is_active"=>"1", "name_bn"=>"কুড়িগ্রাম সদর"),
            array("name"=>"Nageshwari", "district_id"=>"60", "is_active"=>"1", "name_bn"=>"নাগেশ্বরী"),
            array("name"=>"Bhurungamari", "district_id"=>"60", "is_active"=>"1", "name_bn"=>"ভুরুঙ্গামারী"),
            array("name"=>"Phulbari", "district_id"=>"60", "is_active"=>"1", "name_bn"=>"ফুলবাড়ী"),
            array("name"=>"Rajarhat", "district_id"=>"60", "is_active"=>"1", "name_bn"=>"রাজারহাট"),
            array("name"=>"Ulipur", "district_id"=>"60", "is_active"=>"1", "name_bn"=>"উলিপুর"),
            array("name"=>"Chilmari", "district_id"=>"60", "is_active"=>"1", "name_bn"=>"চিলমারী"),
            array("name"=>"Rowmari", "district_id"=>"60", "is_active"=>"1", "name_bn"=>"রৌমারী"),
            array("name"=>"Charrajibpur", "district_id"=>"60", "is_active"=>"1", "name_bn"=>"চর রাজিবপুর"),
            array("name"=>"Sherpur Sadar", "district_id"=>"61", "is_active"=>"1", "name_bn"=>"শেরপুর সদর"),
            array("name"=>"Nalitabari", "district_id"=>"61", "is_active"=>"1", "name_bn"=>"নালিতাবাড়ী"),
            array("name"=>"Sreebordi", "district_id"=>"61", "is_active"=>"1", "name_bn"=>"শ্রীবরদী"),
            array("name"=>"Nokla", "district_id"=>"61", "is_active"=>"1", "name_bn"=>"নকলা"),
            array("name"=>"Jhenaigati", "district_id"=>"61", "is_active"=>"1", "name_bn"=>"ঝিনাইগাতী"),
            array("name"=>"Fulbaria", "district_id"=>"62", "is_active"=>"1", "name_bn"=>"ফুলবাড়ীয়া"),
            array("name"=>"Trishal", "district_id"=>"62", "is_active"=>"1", "name_bn"=>"ত্রিশাল"),
            array("name"=>"Bhaluka", "district_id"=>"62", "is_active"=>"1", "name_bn"=>"ভালুকা"),
            array("name"=>"Muktagacha", "district_id"=>"62", "is_active"=>"1", "name_bn"=>"মুক্তাগাছা"),
            array("name"=>"Mymensingh Sadar", "district_id"=>"62", "is_active"=>"1", "name_bn"=>"ময়মনসিংহ সদর"),
            array("name"=>"Dhobaura", "district_id"=>"62", "is_active"=>"1", "name_bn"=>"ধোবাউড়া"),
            array("name"=>"Phulpur", "district_id"=>"62", "is_active"=>"1", "name_bn"=>"ফুলপুর"),
            array("name"=>"Haluaghat", "district_id"=>"62", "is_active"=>"1", "name_bn"=>"হালুয়াঘাট"),
            array("name"=>"Gouripur", "district_id"=>"62", "is_active"=>"1", "name_bn"=>"গৌরীপুর"),
            array("name"=>"Gafargaon", "district_id"=>"62", "is_active"=>"1", "name_bn"=>"গফরগাঁও"),
            array("name"=>"Iswarganj", "district_id"=>"62", "is_active"=>"1", "name_bn"=>"ঈশ্বরগঞ্জ"),
            array("name"=>"Nandail", "district_id"=>"62", "is_active"=>"1", "name_bn"=>"নান্দাইল"),
            array("name"=>"Tarakanda", "district_id"=>"62", "is_active"=>"1", "name_bn"=>"তারাকান্দা"),
            array("name"=>"Jamalpur Sadar", "district_id"=>"63", "is_active"=>"1", "name_bn"=>"জামালপুর সদর"),
            array("name"=>"Melandah", "district_id"=>"63", "is_active"=>"1", "name_bn"=>"মেলান্দহ"),
            array("name"=>"Islampur", "district_id"=>"63", "is_active"=>"1", "name_bn"=>"ইসলামপুর"),
            array("name"=>"Dewangonj", "district_id"=>"63", "is_active"=>"1", "name_bn"=>"দেওয়ানগঞ্জ"),
            array("name"=>"Sarishabari", "district_id"=>"63", "is_active"=>"1", "name_bn"=>"সরিষাবাড়ী"),
            array("name"=>"Madarganj", "district_id"=>"63", "is_active"=>"1", "name_bn"=>"মাদারগঞ্জ"),
            array("name"=>"Bokshiganj", "district_id"=>"63", "is_active"=>"1", "name_bn"=>"বকশীগঞ্জ"),
            array("name"=>"Barhatta", "district_id"=>"64", "is_active"=>"1", "name_bn"=>"বারহাট্টা"),
            array("name"=>"Durgapur", "district_id"=>"64", "is_active"=>"1", "name_bn"=>"দুর্গাপুর"),
            array("name"=>"Kendua", "district_id"=>"64", "is_active"=>"1", "name_bn"=>"কেন্দুয়া"),
            array("name"=>"Atpara", "district_id"=>"64", "is_active"=>"1", "name_bn"=>"আটপাড়া"),
            array("name"=>"Madan", "district_id"=>"64", "is_active"=>"1", "name_bn"=>"মদন"),
            array("name"=>"Khaliajuri", "district_id"=>"64", "is_active"=>"1", "name_bn"=>"খালিয়াজুরী"),
            array("name"=>"Kalmakanda", "district_id"=>"64", "is_active"=>"1", "name_bn"=>"কলমাকান্দা"),
            array("name"=>"Mohongonj", "district_id"=>"64", "is_active"=>"1", "name_bn"=>"মোহনগঞ্জ"),
            array("name"=>"Purbadhala", "district_id"=>"64", "is_active"=>"1", "name_bn"=>"পূর্বধলা"),
            array("name"=>"Netrokona Sadar", "district_id"=>"64", "is_active"=>"1", "name_bn"=>"নেত্রকোণা সদর"),
            array("name"=>"Eidgaon", "district_id"=>"9", "is_active"=>"1", "name_bn"=>"ঈদগাঁও"),
            array("name"=>"Madhyanagar", "district_id"=>"39", "is_active"=>"1", "name_bn"=>"মধ্যনগর"),
            array("name"=>"Dasar", "district_id"=>"50", "is_active"=>"1", "name_bn"=>"ডাসার")
        );

        foreach ($upazilas as $upazila) {
            Upazila::create([
                'name' => $upazila['name'],
                'district_id' => $upazila['district_id'],
                'is_active' => $upazila['is_active'],
                'name_bn' => $upazila['name_bn']
            ]);
        }
    }
}
